### PR TITLE
Package on PyPI

### PR DESCRIPTION
**Pull request by willprice**
Hi there,

Thanks for the brilliant package. I've uploaded it to PyPI to make it a little easier to install (https://pypi.org/project/torchviz/) I hope you're OK with that? If not let me know and I'll take it down, I'll also transfer ownership to you too.

I've added a Makefile with some useful targets to build the package and upload to PyPI.

### CODE REVIEW

**Comment by szagoruyko** [comment]
This is awesome, thanks a lot!!

**Comment by szagoruyko** [comment]
Hi @willprice , could you please transfer the ownership to me or @albanD? thank you!

**Comment by willprice** [comment]
Hey @szagoruyko,
Of course, I didn't manage to invite you on PyPI as szagoruyko, but there is an account called `alband`, I presume @albanD this is yours? I've invited that account.
@szagoruyko if you can give me your PyPI username I'll transfer ownership

**Comment by albanD** [comment]
Hey!
I got the invite thanks a lot!

**Pull request merged**
